...
      - name: Build project
        run: npm run build

      - name: Ver contenido de dist
        run: |
          echo "Contenido de ./dist:"
          ls -la ./dist

      - name: Copiar web.config a dist
        run: cp web.config dist/

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          package: ./dist
